### ISSUE TITLE
iOS push notifications not working

### ISSUE THREAD

**Issue by ionkorol** [allboatsrise/expo-marketingcloudsdk#21]
Hey guys, 

Need some help. 

I installed the package and added the plugin to expo config.

I am getting notifications on android but not on iOS.

Any idea?

**Comment by andrejpavlovic** [comment]
Check if you have added this code:
https://github.com/allboatsrise/expo-marketingcloudsdk/issues/19#issuecomment-1691783924

and this:
https://github.com/allboatsrise/expo-marketingcloudsdk/issues/19#issuecomment-1691624497

**Comment by ionkorol** [comment]
None of it fixed it. It still says failed when attempting to send message through mobile push
