### ISSUE TITLE
No messages received

### ISSUE THREAD

**Issue by mbiegert** [allboatsrise/expo-marketingcloudsdk#22]
Hi all, I'm currently trying to get push notifications working. So far I've managed to get push notifications on iOS and android devices :partying_face:  However we would like to open a certain screen inside of the app using the OpenDirect method (https://help.salesforce.com/s/articleView?id=sf.mc_mp_opendirect.htm&type=5) However I don't get any message or event inside the app, tried adding listeners all over the place, querying for inbox messages, but nothing showed up.
I do however work with an expo development build, could that be impacting the message delivery?

We are currently still on v48.0.4. I'd be happy for any ideas or hints.

**Comment by andrejpavlovic** [comment]
I haven't implemented any url handling, but if you want to take a look at the documentation and possibly submit a PR I can review and merge it.

iOS
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-iOS/push-notifications/opendirect.html
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-iOS/sdk-implementation/implementation-urlhandling.html

Android
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/sdk-implementation/url-handling.html
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/notifications/customize-notifications.html
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/in-app-message/in-app-messaging.html

I imagine that maybe you can avoid adding native handlers and try to do it via Expo notification listeners - it's just a maybe though. [addNotificationResponseReceivedListener](https://docs.expo.dev/versions/latest/sdk/notifications/#addnotificationresponsereceivedlistenerlistener) or [useLastNotificationResponse](https://docs.expo.dev/versions/latest/sdk/notifications/#uselastnotificationresponse) should be triggered when user interacts with the notification. And then somewhere in the notification object you might be able to find the url that should be opened.

**Comment by andrejpavlovic** [comment]
Also make sure to set `inboxEnabled: true` if you want to receive inbox messages.

**Comment by mbiegert** [comment]
thank you for the prompt response, yes inboxEnabled I've set up in the config plugin, doesn't that mean that that the getMessage() functions should work?

**Comment by andrejpavlovic** [comment]
Yes in theory, you can also use `addLogListener` to help debug what's happening - or check log in xcode/android while the app is running.

**Comment by mbiegert** [comment]
Yeah good point, I set up both listeners but never received anything. But I'll try and dabble into the SDK a bit. Also on iOS I saw some error in the SDK state that some JSON parsing failed. I'll check that out as well.

**Comment by babgyy** [comment]
Hi all, I am facing the exact same issue @mbiegert, did you have any luck ?

**Comment by mbiegert** [comment]
Hi not really yet,no. I also saw that the ios SDK always logs an error that there's an invalid control character when parsing JSON, no idea where that comes from, so I'm still investigating.

**Comment by andrejpavlovic** [comment]
I'm closing this, as it's probably no longer relevant.  I've removed implicit parsing of sdk state when using `getSdkState()`, since it seems like iOS can very well return an invalid JSON string - it now just returns a string.
