### ISSUE TITLE
Example of how to use the plugin

### ISSUE THREAD

**Issue by fbalexandre** [allboatsrise/expo-marketingcloudsdk#25]
Hello. Could you show a simple example to use the plugin? 
I'm using expo 48 and the plugin version "^48.0.4". When I import (import * as MarketingCloud from '@allboatsrise/expo-marketingcloudsdk'), this error returns: "Error: Cannot find native module 'ExpoMarketingCloudSdk', js engine: hermes". 

Thank you very much

**Comment by andrejpavlovic** [comment]
Plugin setup is here:
https://github.com/allboatsrise/expo-marketingcloudsdk#plugin-setup

There is some sample code in this issue:
https://github.com/allboatsrise/expo-marketingcloudsdk/issues/19

Not sure what else I could suggest.

**Comment by andrejpavlovic** [comment]
updated docs to include above mentioned documentation
