### ISSUE TITLE
Allow for dynamic app config changes.

### ISSUE THREAD

**Issue by dizzyd2307** [allboatsrise/expo-marketingcloudsdk#26]
Is there a way to allow for a dynamic change for the app config setup in the app.confgi.js file.
Scenario: user changes location so we would like to plug in a different mobile push app based on different locations.

**Comment by andrejpavlovic** [comment]
No, the values can't be dynamically changed. Not sure how the native SDKs would support that - reinitialization of the SDK/

**Comment by andrejpavlovic** [comment]
stale, closing this
