### ISSUE TITLE
Failed to convert token to data type

### ISSUE THREAD

**Issue by ak-specto** [allboatsrise/expo-marketingcloudsdk#28]
Hi & thank you for creating this library!
I have been trying to solve this issue for a couple of days now, and I can't figure out the solution. When calling 

```
MarketingCloud.setSystemToken(token.data);
```

this gets executed from the library:
```
    AsyncFunction("setSystemToken") { (token: String, promise: Promise) in
      do {
        let token = try ExpoMarketingCloudSdkDeviceToken.init(hexString: token)

        SFMCSdk.requestPushSdk { mp in
          mp.setDeviceToken(token.data)
          promise.resolve(mp.deviceToken())
        }
      } catch {
        promise.reject("invalid-hex-token", "Failed to convert token to data type")
      }
    }
```

and I got back the error `Failed to convert token to data type`.

I have checked multiple things:
- appId, accessToken & serverUrl all get included in the EAS build and are the same on the Salesforce dashboard
- the expo notification token works
- `MarketingCloud.isPushEnabled()` returns `true`
- `addLogListener` returns nothing specific that would indicate an issue
- I have used the boilerplate code from the README example of the library

Do you happen to know what the issue would be?

**Comment by andrejpavlovic** [comment]
Not really sure. Need some more details:
- Expo SDK version
- `expo-notification` version
- what is the value of `token.data` - is it a valid hex string?

**Comment by ak-specto** [comment]
Yes of course:

- `"@allboatsrise/expo-marketingcloudsdk": "^49.1.0"`
- `"expo": "~49.0.16"`,
- `"expo-notifications": "~0.20.1"`,
- Valid string - eg. `ExponentPushToken[QDWdgCPZObVWSHaoe7iF_9]`

**Comment by andrejpavlovic** [comment]
You need to use real push tokens though, not expo tokens.
`Notifications.getDevicePushTokenAsync()`

**Comment by ak-specto** [comment]
My bad, I must have switched it when debugging.

It seems to have gone through now, thank you!!
