### ISSUE TITLE
Expo version 50

### ISSUE THREAD

**Issue by mbiegert** [allboatsrise/expo-marketingcloudsdk#29]
Hi everybody.

Has anybody tried the latest 49.1.0 version here with ExpoV50? We tried a bit today, but it seems to have some problems at least when building android. It complains about different java targets (11 instead of 17).
Anybody having look making it to work with Android already?

**Comment by andrejpavlovic** [comment]
Haven't tried it yet - probably in the next week or two.

**Comment by andrejpavlovic** [comment]
plugin version for expo 50 is out, let me know if there are any issues
