### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by mbiegert** [allboatsrise/expo-marketingcloudsdk#32]
After the upgrade to version 50.1.0 I am seeing this build error building on EAS Build. Am I missing something?

```
Execution failed for task ':allboatsrise-expo-marketingcloudsdk:compileDebugKotlin'.

> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
  ```

![image](https://github.com/allboatsrise/expo-marketingcloudsdk/assets/22346012/7dd3acf5-7871-432f-b7e3-eff97fb643fb)

**Comment by andrejpavlovic** [comment]
sdk 50 requires java 17. You're using SDK 50 right?

**Comment by mbiegert** [comment]
Yeah, I'm sorry, I wasn't actually using the latest version, my apologies. Now it builds!
