### ISSUE TITLE
addInboxResponseListener not working

### ISSUE THREAD

**Issue by lucasoliveirabhs** [allboatsrise/expo-marketingcloudsdk#34]
Hi, I'm trying to retrieve the payload of a received push, but the addInboxResponseListener listener doesn't work, it simply doesn't log any information when the push is received

inboxEnabled is set to true

**Comment by andrejpavlovic** [comment]
expo version?
@allboatsrise/expo-marketingcloudsdk version?

Please copy/paste config. It's `inboxEnabled`, not `inboxEnable`.

**Comment by lucasoliveirabhs** [comment]
> expo version? @allboatsrise/expo-marketingcloudsdk version?
> 
> Please copy/paste config. It's `inboxEnabled`, not `inboxEnable`.

Sorry, in app.json, inboxEnabled is correct, but even so, I can't see the payload of messages either through getMessages or through addInboxResponseListener.

I'm using the version "@allboatsrise/expo-marketingcloudsdk": "^49.0.1",

**Comment by andrejpavlovic** [comment]
iOS or Android?

Anyway, I'm not really going to be able to help you with this, since I've moved onto v50 a while ago.

If you update to latest version, I could have another look.

**Comment by lucasoliveirabhs** [comment]
both, android and ios. I'll update

**Comment by lucasoliveirabhs** [comment]
I updated and I still have the same problem

**Comment by andrejpavlovic** [comment]
You need to call `MarketingCloud.refreshInbox()` I think

**Comment by andrejpavlovic** [comment]
It should also trigger automatically whenever you put the app into background and then back into foreground. Inbox is checked automatically any time you bring the app into foreground.

**Comment by lucasoliveirabhs** [comment]
I noticed that the expo listeners (addNotificationReceivedListener, addNotificationResponseReceivedListener) also don't work when a message is sent from salesforce, only on Android, but sending from https://expo.dev/notifications works.

**Comment by andrejpavlovic** [comment]
Marked as stale, closing.
