### ISSUE TITLE
ExpoMarketingCloudSdk

### ISSUE THREAD

**Issue by RamboWasReal** [allboatsrise/expo-marketingcloudsdk#36]
hey, i get Error: Cannot find native module 'ExpoMarketingCloudSdk', js engine: hermes when i try to open app with prebuild.

I follow step on README, but i dont know why i got this error

in my app.config.js
 [
        '@allboatsrise/expo-marketingcloudsdk',
        {
          appId: '...',
          accessToken: '....',
          serverUrl:
            '....',
        },
      ],
      'expo-notifications',
    ],

expo version: 50.0.17
allboatsrise/expo-marketingcloudsdk": "^50.2.1"

**Comment by andrejpavlovic** [comment]
Did you fully remove `ios`/`android` folder and try to prebuild from scratch?

**Comment by RamboWasReal** [comment]
Yes

**Comment by andrejpavlovic** [comment]
clean npm/yarn install? Is the node module there?

**Comment by RamboWasReal** [comment]
i try all of that,and  i saw the node module

**Comment by RamboWasReal** [comment]
i re-try to remove node_module folder, prebuild with flag --clean, but i get same error at the end

btw thantks for your quick answer!

**Comment by andrejpavlovic** [comment]
Not really sure how else I can help.  If you can reproduce this in a new project and share it, I can take a closer look.

**Comment by RamboWasReal** [comment]
hey finally it's working !, 

i restart trom scratch and now all is ok..

thx again for your quick answer

i will close this issue !
