### ISSUE TITLE
Impossible to run app in Expo GO

### ISSUE THREAD

**Issue by danny88dam** [allboatsrise/expo-marketingcloudsdk#38]
Hi, I'm try to integrate this package in my project.

I follow the instruction in README file, but I'm getting this error message
Error: Cannot find native module 'ExpoMarketingCloudSdk', js engine: hermes
![image](https://github.com/allboatsrise/expo-marketingcloudsdk/assets/49842498/a40501dd-e371-48c8-b3bb-2e102008fecb)

Here the installed packages
![image](https://github.com/allboatsrise/expo-marketingcloudsdk/assets/49842498/614e651d-7bc5-4f33-8889-94fe5f4becde)

Here a piece of code that throws the error, specifically at MarketingCloud.setSystemToken (the very first call to MarketingCloud utilities)
`; (async () => {
        
        ...

        const token = await Notifications.getDevicePushTokenAsync()
        // let Marketing Cloud SDK the value of current push token
        try{
          MarketingCloud.setSystemToken(token.data)
            .then(response => {
              setStatus(response ?? "null response from MC")
            })
  
          // In rare situations a push token may be changed by the push notification service while the app is running.
          const subscription = Notifications.addPushTokenListener((newToken) => {
            MarketingCloud.setSystemToken(newToken.data)
          })
          cleanup = () => subscription.remove()
        }
        catch(e: any){
          setStatus(e.message)
        }
      })()
`
The error is thrown only on Expo Go, when I build the app (via eas) for internal distribution all seems to work well.

Thank you

**Comment by andrejpavlovic** [comment]
This cannot work in Expo Go since you have to use custom native libraries. Look into build a custom client.

**Comment by danny88dam** [comment]
Ok, thank you.

Maybe can be usefull to know building app via `eas build` with developmentClient: true
![image](https://github.com/allboatsrise/expo-marketingcloudsdk/assets/49842498/5075cae2-46d9-49c9-ada8-9372b325a922)
can help to avoid the problem

\D
