### ISSUE TITLE
URL handling for iOS and Android

### ISSUE THREAD

**Issue by jakac13** [allboatsrise/expo-marketingcloudsdk#43]
Hi,

we have some experience with URL handling for React Native plugin where URL handling for push notifications and in-app messages is handled through native code. I do wonder how do we set up URL handling with expo plugin?

After logging the notification, there seems to be no URL property. Push is sent through journey with open behavior of "Go to Web URL" with a url link. Is there something we are forgetting? I used `Notifications.getLastNotificationResponseAsync()`.

Also how would URL handling for in-app messages work here?

![image](https://github.com/user-attachments/assets/087db37d-c1cd-4351-b3ba-575bf9be6423)

I did find this comment from 2023, where it is said that url handling was not implemented.
https://github.com/allboatsrise/expo-marketingcloudsdk/issues/22#issuecomment-1737557976

---

**EDIT: For in-app messages we did notice the marketingcloudsdk log: 'URL https://www.link.com/ was NOT handled - the URL handling delegate method was NOT implemented or delegate nil'

also we did find the url and mediaUrl inside of target object which is probably intended for FCM...
![image](https://github.com/user-attachments/assets/15b33786-75a2-4fd4-89ff-92cb08373275)

**Comment by andrejpavlovic** [comment]
I think you'd want to use something like `Notification.useLastNotificationResponse()`

From https://docs.expo.dev/versions/latest/sdk/notifications/#uselastnotificationresponse:
```typescript
import * as Notifications from 'expo-notifications';
import { Linking } from 'react-native';

export default function App() {
  const lastNotificationResponse = Notifications.useLastNotificationResponse();
  React.useEffect(() => {
    if (
      lastNotificationResponse &&
      lastNotificationResponse.notification.request.content.data.url &&
      lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER
    ) {
      Linking.openURL(lastNotificationResponse.notification.request.content.data.url);
    }
  }, [lastNotificationResponse]);
  return (
    // Your app content
  );
}
```

**Comment by andrejpavlovic** [comment]
Stale, please re-open if issue persists.

**Comment by andrejpavlovic** [comment]
Stale, please re-open if issue persists.

**Comment by anaalexandraisaias** [comment]
Hi @andrejpavlovic, 

I'm having a similar situation with the 'URL https://www.link.com/ was NOT handled - the URL handling delegate method was NOT implemented or delegate nil'

In the file where I handle the notifications I have this logic for dealing with the link sent by the Salesforce notification. I've logged it and I get the correct link, and if the user is authenticated in the app it redirects correctly, but if the user is not authenticated I get the error above and it simply goes to the homepage post login. 

`const handleNotificationResponse = (response: NotificationResponse) => {
      const data = response.notification.request.content.data;

      const trigger = response?.notification?.request?.trigger;
      const screen = (trigger as Notifications.PushNotificationTrigger).payload
        ?._od as Href;

      logger.debug(
        `Notification response received: ${JSON.stringify(response.notification)}`
      );
      logger.debug(`Notification trigger data: ${JSON.stringify(trigger)}`);

      const url = screen ?? data?.url;

      if (url) {
        router.replace(url);
      } else {
        logger.debug('No URL found in notification response');
      }
    };

    const responseListener =
      Notifications.addNotificationResponseReceivedListener(
        handleNotificationResponse
      );
`

Any idea on what steps I could take to debug this or to fix this situation if you know how?

Thank you so much :)
