### ISSUE TITLE
getTags() doesn't work on iOS

### ISSUE THREAD

**Issue by danny88dam** [allboatsrise/expo-marketingcloudsdk#44]
Hi, we meet again 😅

I'm try to implement tag assignment via `addTag`.

The business logic is that every startup the app checks for the existance of tag starting with PRX_, if not it adds it.

On Android everything works fine, while on iOS `getTags()` returns undefined.

I think there is something wrong with the swift code

**Comment by andrejpavlovic** [comment]
fix released in `51.0.5`
