### ISSUE TITLE
Unable to install `expo-marketingcloudsdk` package

### ISSUE THREAD

**Issue by byFadili** [allboatsrise/expo-marketingcloudsdk#5]
Hi !
Thank you very much for putting up this helpful package.
I am currently trying to use Marketing Cloud MobilePush in an expo project, but I get a 404 NPM Registry Error when I try to install `expo-marketingcloudsdk` package.

## Issue description
NPM 404 Error when trying to install `expo-marketingcloudsdk` package as per the current documentation

## To Reproduce
run `yarn add expo-marketingcloudsdk` or `npm install expo-marketingcloudsdk --save`

## Screenshots/Code
```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/expo-marketingcloudsdk - Not found
npm ERR! 404 
npm ERR! 404  'expo-marketingcloudsdk@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Thank you in advance for your help !

**Comment by andrejpavlovic** [comment]
It should be `npm install @allboatsrise/expo-marketingcloudsdk` not `npm install expo-marketingcloudsdk`. I've updated the readme to fix the instructions. Fixed in PR https://github.com/allboatsrise/expo-marketingcloudsdk/pull/7

**Comment by byFadili** [comment]
Thank you @andrejpavlovic
