### ISSUE TITLE
 Expo SDK 52

### ISSUE THREAD

**Issue by humbertocruz** [allboatsrise/expo-marketingcloudsdk#50]
Any preview of the 52 version for Expo SDK 52, or can I use the last 51?

**Comment by andrejpavlovic** [comment]
In theory it should work. I managed to compile for Android just fine, for iOS I haven't tried. I also haven't enabled new arch, but it should work in theory.

**Comment by andrejpavlovic** [comment]
Closing this as it seems to be working just fine with SDK 52.

**Comment by lucasoliveirabhs** [comment]
I noticed that the addInboxResponseListener method is not working when I update to exposdk52, but in 51 it works normally

**Comment by andrejpavlovic** [comment]
@lucasoliveirabhs please open new issue and provide more info
